/**:
  ros__parameters:
    camera_name: "camera_1"
    frame_id: "camera_top/camera_link"
    pixel_format: bgr8
    serial_no: 243501468
    camera_info_url: "file:///home/stust/awf_stust/src/autoware/sensor_component/external/lucid_vision_driver/config/test.yaml"
    fps: 20
    horizontal_binning: 1 # resize horizontal resolution/horizontal_binning
    vertical_binning: 1 # resize horizontal resolution/vertical_binning
    enable_rectifying: false
    enable_compressing: false
    use_default_device_settings: false
    # if you use_default_device_settings: true, the following settings are ignored.
    # ROS driver will use the default device settings of the camera.
    exposure_auto: true
    exposure_target: 187
    gain_auto: true
    gain_target: 1
    gamma_target: 1.0
    image_horizontal_flip: false
    image_vertical_flip: false
